/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Entity1 } from "./Entity1";
import { Entity1CountArgs } from "./Entity1CountArgs";
import { Entity1FindManyArgs } from "./Entity1FindManyArgs";
import { Entity1FindUniqueArgs } from "./Entity1FindUniqueArgs";
import { DeleteEntity1Args } from "./DeleteEntity1Args";
import { Entity1Service } from "../entity1.service";
@graphql.Resolver(() => Entity1)
export class Entity1ResolverBase {
  constructor(protected readonly service: Entity1Service) {}

  async _entity1sMeta(
    @graphql.Args() args: Entity1CountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Entity1])
  async entity1s(
    @graphql.Args() args: Entity1FindManyArgs
  ): Promise<Entity1[]> {
    return this.service.entity1s(args);
  }

  @graphql.Query(() => Entity1, { nullable: true })
  async entity1(
    @graphql.Args() args: Entity1FindUniqueArgs
  ): Promise<Entity1 | null> {
    const result = await this.service.entity1(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Entity1)
  async deleteEntity1(
    @graphql.Args() args: DeleteEntity1Args
  ): Promise<Entity1 | null> {
    try {
      return await this.service.deleteEntity1(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
