/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity1WhereUniqueInput } from "./Entity1WhereUniqueInput";
import { ValidateNested } from "class-validator";
import { Type } from "class-transformer";

@ArgsType()
class DeleteEntity1Args {
  @ApiProperty({
    required: true,
    type: () => Entity1WhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => Entity1WhereUniqueInput)
  @Field(() => Entity1WhereUniqueInput, { nullable: false })
  where!: Entity1WhereUniqueInput;
}

export { DeleteEntity1Args as DeleteEntity1Args };
