/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, Entity1 as PrismaEntity1 } from "@prisma/client";

export class Entity1ServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.Entity1CountArgs, "select">): Promise<number> {
    return this.prisma.entity1.count(args);
  }

  async entity1s(args: Prisma.Entity1FindManyArgs): Promise<PrismaEntity1[]> {
    return this.prisma.entity1.findMany(args);
  }
  async entity1(
    args: Prisma.Entity1FindUniqueArgs
  ): Promise<PrismaEntity1 | null> {
    return this.prisma.entity1.findUnique(args);
  }
  async createEntity1(args: Prisma.Entity1CreateArgs): Promise<PrismaEntity1> {
    return this.prisma.entity1.create(args);
  }
  async updateEntity1(args: Prisma.Entity1UpdateArgs): Promise<PrismaEntity1> {
    return this.prisma.entity1.update(args);
  }
  async deleteEntity1(args: Prisma.Entity1DeleteArgs): Promise<PrismaEntity1> {
    return this.prisma.entity1.delete(args);
  }
}
