/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { Entity1Service } from "../entity1.service";
import { Entity1CreateInput } from "./Entity1CreateInput";
import { Entity1 } from "./Entity1";
import { Entity1FindManyArgs } from "./Entity1FindManyArgs";
import { Entity1WhereUniqueInput } from "./Entity1WhereUniqueInput";
import { Entity1UpdateInput } from "./Entity1UpdateInput";

export class Entity1ControllerBase {
  constructor(protected readonly service: Entity1Service) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Entity1 })
  async createEntity1(
    @common.Body() data: Entity1CreateInput
  ): Promise<Entity1> {
    return await this.service.createEntity1({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Entity1] })
  @ApiNestedQuery(Entity1FindManyArgs)
  async entity1s(@common.Req() request: Request): Promise<Entity1[]> {
    const args = plainToClass(Entity1FindManyArgs, request.query);
    return this.service.entity1s({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Entity1 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async entity1(
    @common.Param() params: Entity1WhereUniqueInput
  ): Promise<Entity1 | null> {
    const result = await this.service.entity1({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Entity1 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateEntity1(
    @common.Param() params: Entity1WhereUniqueInput,
    @common.Body() data: Entity1UpdateInput
  ): Promise<Entity1 | null> {
    try {
      return await this.service.updateEntity1({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Entity1 })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteEntity1(
    @common.Param() params: Entity1WhereUniqueInput
  ): Promise<Entity1 | null> {
    try {
      return await this.service.deleteEntity1({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
