/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity1WhereInput } from "./Entity1WhereInput";
import { ValidateNested, IsOptional } from "class-validator";
import { Type } from "class-transformer";

@InputType()
class Entity1ListRelationFilter {
  @ApiProperty({
    required: false,
    type: () => Entity1WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity1WhereInput)
  @IsOptional()
  @Field(() => Entity1WhereInput, {
    nullable: true,
  })
  every?: Entity1WhereInput;

  @ApiProperty({
    required: false,
    type: () => Entity1WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity1WhereInput)
  @IsOptional()
  @Field(() => Entity1WhereInput, {
    nullable: true,
  })
  some?: Entity1WhereInput;

  @ApiProperty({
    required: false,
    type: () => Entity1WhereInput,
  })
  @ValidateNested()
  @Type(() => Entity1WhereInput)
  @IsOptional()
  @Field(() => Entity1WhereInput, {
    nullable: true,
  })
  none?: Entity1WhereInput;
}
export { Entity1ListRelationFilter as Entity1ListRelationFilter };
