/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity1WhereInput } from "./Entity1WhereInput";
import { IsOptional, ValidateNested, IsInt } from "class-validator";
import { Type } from "class-transformer";
import { Entity1OrderByInput } from "./Entity1OrderByInput";

@ArgsType()
class Entity1FindManyArgs {
  @ApiProperty({
    required: false,
    type: () => Entity1WhereInput,
  })
  @IsOptional()
  @ValidateNested()
  @Field(() => Entity1WhereInput, { nullable: true })
  @Type(() => Entity1WhereInput)
  where?: Entity1WhereInput;

  @ApiProperty({
    required: false,
    type: [Entity1OrderByInput],
  })
  @IsOptional()
  @ValidateNested({ each: true })
  @Field(() => [Entity1OrderByInput], { nullable: true })
  @Type(() => Entity1OrderByInput)
  orderBy?: Array<Entity1OrderByInput>;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  skip?: number;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsOptional()
  @IsInt()
  @Field(() => Number, { nullable: true })
  @Type(() => Number)
  take?: number;
}

export { Entity1FindManyArgs as Entity1FindManyArgs };
