/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ArgsType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { Entity1WhereInput } from "./Entity1WhereInput";
import { Type } from "class-transformer";

@ArgsType()
class Entity1CountArgs {
  @ApiProperty({
    required: false,
    type: () => Entity1WhereInput,
  })
  @Field(() => Entity1WhereInput, { nullable: true })
  @Type(() => Entity1WhereInput)
  where?: Entity1WhereInput;
}

export { Entity1CountArgs as Entity1CountArgs };
